### ISSUE TITLE
Fix F14/F15 keys for native Apple Keyboards (They should not change brightness)

### ISSUE THREAD

**Issue by tomtastic** [nhurden/MediaKeyTap#10]
See : https://github.com/MonitorControl/MonitorControl/issues/100#issuecomment-653450566
F14 and F15 should not be intercepted for these keyboards as Brightness keys.

For these Apple keyboards with F13-F19 keys available (eg. 'Magic Keyboard with Numeric Keypad'), the native brightness controls (media keys) are on the F1+F2 key positions, not the intercepted :
```
Key Down
	Characters:	
	Unicode:		63249 / 0xf711
	Keys:		F14
	Key Code:	107 / 0x6b
	Modifiers:	8388864 / 0x800100 ⓘ

Key Down
	Characters:	
	Unicode:		63250 / 0xf712
	Keys:		F15
	Key Code:	113 / 0x71
	Modifiers:	8388864 / 0x800100 ⓘ
```

**Comment by nhurden** [comment]
That doesn't seem to be part of this library, but https://github.com/the0neyouseek/MediaKeyTap instead (a fork).

See also https://github.com/the0neyouseek/MediaKeyTap/commit/d02f865ea962d5811375ddd047525baf409fb2b0
