### ISSUE TITLE
macOS Sonoma

### ISSUE THREAD

**Issue by rokach** [nhurden/MediaKeyTap#16]
Hi,
As I know this framework not work in macOS Sonoma any update soon?

**Comment by nhurden** [comment]
I've just tried the example app on Sonoma and everything seems to still work. Do you have your app allowed in the accessibility settings?

**Comment by rokach** [comment]
It was my problem sorry, anyway is it possible to handle Touch Bar slider
(not tap) with MediaKeyTap?
Thank you!
