### ISSUE TITLE
Do you know how to use the media key like this project , no need to allowed from Accessibility ?

### ISSUE THREAD

**Issue by michaelmou** [nhurden/MediaKeyTap#3]
<img width="615" alt="2018-09-28 23 04 10" src="https://user-images.githubusercontent.com/5761759/46216727-d1e60180-c372-11e8-8d6f-529b2d5f0bc0.png">

Thanks

**Comment by nhurden** [comment]
Doesn't that project also need to be enabled in the accessibility settings?
https://github.com/milgra/highsierramediakeyenabler/issues/55

**Comment by nhurden** [comment]
As far as I can tell, it actually isn't possible to have an active (non-listen-only) CGEvent tap without enabling the accessibility setting:
https://developer.apple.com/videos/play/wwdc2018/702/
